services:
  mongo:
    container_name: test-task-mongo
    image: mongo:6.0
    entrypoint:
      - bash
      - -c
      - |
        exec docker-entrypoint.sh $$@
    command: mongod --replSet rs --bind_ip_all --keyFile config/keyfile --quiet --logpath /dev/null
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - test-task
    ports:
      - 27017:27017
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .dev/mongo/config/keyfile:/config/keyfile
      - type: volume
        source: mongodb
        target: /data/db
      - type: volume
        source: mongodb-cfg
        target: /data/configdb
  # mongo-replicator creates a replica set for transaction support
  mongo-replicator:
    container_name: test-task-mongo-replicator
    image: mongo:6.0
    entrypoint:
      - bash
      - -c
      - |
        cd /scripts
        chmod +x /setup.sh
        bash /setup.sh
    volumes:
      - ./bin/setup.sh:/setup.sh
      - ./bin:/scripts
    environment:
      - HOST=mongo
      - PORT=27017
      - USERNAME=root
      - PASSWORD=root
      - REPLICA_SET_NAME=rs
    networks:
      - test-task
    depends_on:
      - mongo
  redis:
    container_name: test-task-redis
    image: redis:5.0.5
    command: redis-server --appendonly yes
    hostname: redis
    networks:
      - test-task
    ports:
      - 6379:6379
  api:
    container_name: test-task-api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: development
      args:
        NODE_ENV: development
        APP_ENV: development
    networks:
      - test-task
    volumes:
      - ./apps/api/src:/app/apps/api/src
      - mailer-volume:/app/packages/mailer
    ports:
      - 3001:3001
    depends_on:
      - redis
      - mongo-replicator
  migrator:
    container_name: test-task-migrator
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile.migrator
      target: development
      args:
        NODE_ENV: development
        APP_ENV: development
    networks:
      - test-task
    volumes:
      - ./apps/api/src:/app/apps/api/src
    depends_on:
      - mongo-replicator
  scheduler:
    container_name: test-task-scheduler
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile.scheduler
      target: development
      args:
        NODE_ENV: development
        APP_ENV: development
    networks:
      - test-task
    volumes:
      - ./apps/api/src:/app/apps/api/src
    depends_on:
      - mongo-replicator
  web:
    container_name: test-task-web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      target: development
      args:
        NODE_ENV: development
        APP_ENV: development
    volumes:
      - ./apps/web/src:/app/apps/web/src
      - ./apps/web/public:/app/apps/web/public
    networks:
      - test-task
    ports:
      - 3002:3002
  mailer:
    container_name: test-task-mailer
    build:
      context: .
      dockerfile: ./packages/mailer/Dockerfile
      target: development
      args:
        NODE_ENV: development
        APP_ENV: development
    volumes:
      - mailer-volume:/app/packages/mailer/dist
      - ./packages/mailer/emails:/app/packages/mailer/emails
      - ./packages/mailer/src:/app/packages/mailer/src
    networks:
      - test-task
    ports:
      - 3003:3003
networks:
  test-task:
    name: test-task-network

volumes:
  mongodb:
  mongodb-cfg:
  mailer-volume:
